/* USER BOUND */
/* DONT NEED IN ACTUAL APP FOR PROOFING PURPOSES ONLY */
export const USER_BOUND_INITIALIZE = "USER_BOUND_INITIALIZE";
export const USER_BOUND_UPDATE_ON_ZOOM = "USER_BOUND_UPDATE_ON_ZOOM";
export const USER_BOUND_UPDATE_ON_MOVE = "USER_BOUND_UPDATE_ON_MOVE";

/* Buffered Extents */
export const BUFFERED_EXTENTS_INITIALIZE_SUCCESS =
  "BUFFERED_EXTENTS_INITIALIZE_SUCCESS";
export const BUFFERED_EXTENTS_INITIALIZE_FAIL =
  "BUFFERED_EXTENTS_INITIALIZE_FAIL";
export const BUFFERED_EXTENTS_UPDATE_ON_NO_INTERSECTIONS_REQUEST =
  "BUFFERED_EXTENTS_UPDATE_ON_NO_INTERSECTIONS_REQUEST";
export const BUFFERED_EXTENTS_UPDATE_ON_ONE_INTERSECTIONS_REQUEST =
  "BUFFERED_EXTENTS_UPDATE_ON_ONE_INTERSECTIONS_REQUEST";
export const BUFFERED_EXTENTS_UPDATE_ON_TWO_INTERSECTIONS_REQUEST =
  "BUFFERED_EXTENTS_UPDATE_ON_TWO_INTERSECTIONS_REQUEST";
export const BUFFERED_EXTENTS_UPDATE_ON_THREE_INTERSECTIONS_REQUEST =
  "BUFFERED_EXTENTS_UPDATE_ON_THREE_INTERSECTIONS_REQUEST";
export const BUFFERED_EXTENTS_UPDATE_SUCCESS =
  "BUFFERED_EXTENTS_UPDATE_SUCCESS";
export const BUFFERED_EXTENTS_UPDATE_FAIL = "BUFFERED_EXTENTS_UPDATE_FAIL";
export const BUFFERED_EXTENTS_REMOVE_FURTHEST_REQUEST =
  "BUFFERED_EXTENTS_REMOVE_FURTHEST_REQUEST";
export const BUFFERED_EXTENTS_REMOVE_FURTHEST_SUCCESS =
  "BUFFERED_EXTENTS_REMOVE_FURTHEST_SUCCESS";
export const BUFFERED_EXTENTS_REMOVE_FURTHEST_FAIL =
  "BUFFERED_EXTENTS_REMOVE_FURTHEST_FAIL";
export const BUFFERED_EXTENTS_NOTHING_TO_UPDATE =
  "BUFFERED_EXTENTS_NOTHING_TO_UPDATE";

/* Cached Data */
export const CACHED_DATA_INITIALIZE_SUCCESS = "CACHED_DATA_INITIALIZE_SUCCESS";
export const CACHED_DATA_INITIALIZE_FAIL = "CACHED_DATA_INITIALIZE_FAIL";
export const CACHED_DATA_UPDATE_REQUEST = "CACHED_DATA_UPDATE_REQUEST";
export const CACHED_DATA_UPDATE_SUCCESS = "CACHED_DATA_UPDATE_SUCCESS";
export const CACHED_DATA_UPDATE_FAIL = "CACHED_DATA_UPDATE_FAIL";
export const CACHED_DATA_REMOVE_FURTHEST_REQUEST =
  "CACHED_DATA_REMOVE_FURTHEST_REQUEST";
export const CACHED_DATA_REMOVE_FURTHEST_SUCCESS =
  "CACHED_DATA_REMOVE_FURTHEST_SUCCESS";
export const CACHED_DATA_REMOVE_FURTHEST_FAIL =
  "CACHED_DATA_REMOVE_FURTHEST_FAIL";

/* User Settings */
export const USER_SETTINGS_ENABLE_POSITION_TRACKING =
  "USER_SETTINGS_ENABLE_POSITION_TRACKING";
export const USER_SETTINGS_DISABLE_POSITION_TRACKING =
  "USER_SETTINGS_DISABLE_POSITION_TRACKING";
export const USER_SETTINGS_ENABLE_PROOF_MAP = "USER_SETTINGS_ENABLE_PROOF_MAP";
export const USER_SETTINGS_DISABLE_PROOF_MAP =
  "USER_SETTINGS_DISABLE_PROOF_MAP";
export const USER_SETTINGS_ENABLE_SHOW_POSITION =
  "USER_SETTINGS_ENABLE_SHOW_POSITION";
export const USER_SETTINGS_DISABLE_SHOW_POSITION =
  "USER_SETTINGS_DISABLE_SHOW_POSITION";
export const USER_SETTINGS_UPDATE_CURRENT_POSITION_REQUEST =
  "USER_SETTINGS_UPDATE_CURRENT_POSITION_REQUEST";
export const USER_SETTINGS_UPDATE_CURRENT_POSITION_SUCCESS =
  "USER_SETTINGS_UPDATE_CURRENT_POSITION_SUCCESS";
export const USER_SETTINGS_UPDATE_CURRENT_POSITION_FAIL =
  "USER_SETTINGS_UPDATE_CURRENT_POSITION_FAIL";
export const USER_SETTINGS_UPDATE_WATCH_ID =
  "USER_SETTINGS_UPDATE_WATCH_ID_SUCCESS";
export const USER_SETTINGS_REMOVE_WATCH_ID = "USER_SETTINGS_REMOVE_WATCH_ID";
export const USER_SETTINGS_UPDATE_WATCH_ID_FAIL =
  "USER_SETTINGS_UPDATE_WATCH_ID_FAIL";

/* Recorded Position */
export const RECORDED_POSITION_UPDATE_REQUEST =
  "RECORDED_POSITION_UPDATE_REQUEST";
export const RECORDED_POSITION_UPDATE_SUCCESS =
  "RECORDED_POSITION_UPDATE_SUCCESS";
export const RECORDED_POSITION_UPDATE_FAIL = "RECORDED_POSITION_UPDATE_FAIL";
