/* USER BOUND */
/* DONT NEED IN ACTUAL APP FOR PROOFING PURPOSES ONLY */
export const USER_BOUND_INITIALIZE = "USER_BOUND_INITIALIZE";
export const USER_BOUND_UPDATE_ON_ZOOM = "USER_BOUND_UPDATE_ON_ZOOM";
export const USER_BOUND_UPDATE_ON_MOVE = "USER_BOUND_UPDATE_ON_MOVE";

/* Buffered Extents */
export const BUFFERED_EXTENTS_INITIALIZE_REQUEST =
  "BUFFERED_EXTENTS_INITIALIZE_REQUEST";
export const BUFFERED_EXTENTS_INITIALIZE_SUCCESS =
  "BUFFERED_EXTENTS_INITIALIZE_SUCCESS";
export const BUFFERED_EXTENTS_INITIALIZE_FAIL =
  "BUFFERED_EXTENTS_INITIALIZE_FAIL";
export const BUFFERED_EXTENTS_UPDATE_ON_NO_INTERSECTIONS_REQUEST =
  "BUFFERED_EXTENTS_UPDATE_ON_NO_INTERSECTIONS_REQUEST";
export const BUFFERED_EXTENTS_UPDATE_ON_ONE_INTERSECTIONS_REQUEST =
  "BUFFERED_EXTENTS_UPDATE_ON_ONE_INTERSECTIONS_REQUEST";
export const BUFFERED_EXTENTS_UPDATE_ON_TWO_INTERSECTIONS_REQUEST =
  "BUFFERED_EXTENTS_UPDATE_ON_TWO_INTERSECTIONS_REQUEST";
export const BUFFERED_EXTENTS_UPDATE_ON_THREE_INTERSECTIONS_REQUEST =
  "BUFFERED_EXTENTS_UPDATE_ON_THREE_INTERSECTIONS_REQUEST";
export const BUFFERED_EXTENTS_UPDATE_SUCCESS =
  "BUFFERED_EXTENTS_UPDATE_SUCCESS";
export const BUFFERED_EXTENTS_UPDATE_FAIL = "BUFFERED_EXTENTS_UPDATE_FAIL";
export const BUFFERED_EXTENTS_REMOVE_FURTHEST_REQUEST = "BUFFERED_EXTENTS_REMOVE_FURTHEST_REQUEST";
export const BUFFERED_EXTENTS_REMOVE_FURTHEST_SUCCESS = "BUFFERED_EXTENTS_REMOVE_FURTHEST_SUCCESS";
export const BUFFERED_EXTENTS_REMOVE_FURTHEST_FAIL = "BUFFERED_EXTENTS_REMOVE_FURTHEST_FAIL";
export const BUFFERED_EXTENTS_NOTHING_TO_UPDATE = "BUFFERED_EXTENTS_NOTHING_TO_UPDATE";

/* Cached Data */
export const CACHED_DATA_INITIALIZE_REQUEST = "CACHED_DATA_INITIALIZE_REQUEST";
export const CACHED_DATA_INITIALIZE_SUCCESS = "CACHED_DATA_INITIALIZE_SUCCESS";
export const CACHED_DATA_INITIALIZE_FAIL = "CACHED_DATA_INITIALIZE_FAIL";
export const CACHED_DATA_UPDATE_REQUEST = "CACHED_DATA_UPDATE_REQUEST";
export const CACHED_DATA_UPDATE_SUCCESS = "CACHED_DATA_UPDATE_SUCCESS";
export const CACHED_DATA_UPDATE_FAIL = "CACHED_DATA_UPDATE_FAIL";
export const CACHED_DATA_REMOVE_FURTHEST_REQUEST = "CACHED_DATA_REMOVE_FURTHEST_REQUEST";
export const CACHED_DATA_REMOVE_FURTHEST_SUCCESS = "CACHED_DATA_REMOVE_FURTHEST_SUCCESS";
export const CACHED_DATA_REMOVE_FURTHEST_FAIL = "CACHED_DATA_REMOVE_FURTHEST_FAIL";
